### ISSUE TITLE
论文里的一些疑惑的地方

### ISSUE THREAD

**Issue by songyonger** [xushoukai/Generative-Low-bitwidth-Data-Free-Quantization#9]
您好，您论文里提到
①warm-up阶段只更新生成器G;
②fine-tuning阶段固定量化模型中的BN statistics
请问这两部分在代码里的哪部分呢?
另外代码里在前四个epoch 里unfreeze_model，不固定激活范围，在后面的epoch里都选择fix激活范围，这是为什么呢?

**Comment by HaoKun-Li** [comment]
关于问题①，可以看以下截图的代码，在warm-up阶段只更新了生成器G，在finetune阶段同时更新生成器G和量化模型;
![image](https://user-images.githubusercontent.com/34161960/233935478-f5e6afcc-b4c8-4f51-8d0f-c63b5ed50c4a.png)
关于问题②，可以看以下截图的代码，在train的时候，特意把量化模型置为eval()模式。在此模式下，量化模型中的BN statistics就是固定住的，不会更新了。
![image](https://user-images.githubusercontent.com/34161960/233940372-bbf81a87-fd8a-4a6c-9b53-f5125033aac2.png)

在前四个epoch 里unfreeze_model，不固定激活范围，是因为前四个epoch里生成器逐渐稳定，生成的图像逐渐接近原始数据分布，此时让激活范围根据生成的样本进行调整。
后面的epoch里都选择fix激活范围，是为了降低量化模型参数的收敛难度，让微调过程更加稳定。

**Comment by songyonger** [comment]
谢谢!
